name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version:
          - '3.9'
          - '3.12'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install subset of dev deps
        run: pip install flit pytest pytest-playwright

      - name: Install production deps
        run: flit install --deps production

      - name: Install browsers
        # Install just one browser instead of the default three.
        # https://playwright.dev/python/docs/browsers#managing-browser-binaries
        run: playwright install chromium

      - name: Run end-to-end test
        # We want to make sure there aren't hidden dependencies
        # on dev tools in production code, and that it still works
        # when dependencies aren't pinned.
        run: pytest -k test_app

      - name: Install dev dependencies
        run: pip install -r requirements-dev.txt

      - name: Run full tests
        run: ./ci.sh

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: test-results/
